### ISSUE TITLE
How to find TSO Offset in the kernel?

### ISSUE THREAD

**Issue by peterzheng98** [saagarjha/TSOEnabler#1]
How to find TSO Offset in the kernel?

**Comment by saagarjha** [comment]
Hi, sorry for the delay. The TSO offset is the offset from the thread pointer that the flag for "is this process Rosetta" is stored. I don't actually know what this flag is called, but it's checked before deciding whether to enable TSO. On the DTK's A12Z (t8020) processor TSO is enabled by setting bit 1 << 16 of the s3_0_c15_c9_0 register. For example, consider this snippet from the 20D5029f kernel:

```asm
fffffe00071efb84        mrs     x3, TPIDR_EL1
fffffe00071efb88        ldr     x0, [x3, #0x4e8]        ; Latency: 4
fffffe00071efb8c        cbz     x0, 0xfffffe00071efbb8
fffffe00071efb90        mrs     x0, S3_0_C15_C9_0
fffffe00071efb94        orr     x0, x0, #0x10000
fffffe00071efb98        dsb     sy
fffffe00071efb9c        msr     S3_0_C15_C9_0, x0
fffffe00071efba0        isb
```

On the DTK this offset has remained at 0x4e8 for every build but the first beta, just FYI. I haven't completely figured out what is going on for the M1 (t8101) chip but if I had to guess the flag is set on actlr_el1 in this code segment:

```asm
fffffe00071f7bac        mrs     x3, TPIDR_EL1
fffffe00071f7bb0        ldr     x0, [x3, #0x4f8]
fffffe00071f7bb4        cbz     x0, 0xfffffe00071f7bf8
fffffe00071f7bb8        mrs     x0, ACTLR_EL1
fffffe00071f7bbc        orr     x0, x0, #0x2
fffffe00071f7bc0        orr     x0, x0, #0x70
fffffe00071f7bc4        dsb     sy
fffffe00071f7bc8        msr     ACTLR_EL1, x0
fffffe00071f7bcc        isb
```

On that processor you wouldn't need to mess with cluster binding so you might be able to get it to work just by setting `TSO_OFFSET` to 0x4f8.

**Comment by roolebo** [comment]
@saagarjha did you look what syscall provides the capabilities to user-space? Rosetta 2 doesn't require any kernel extensions what makes me think there should be a thread flag or a syscall that could be used without a kernel extension

**Comment by saagarjha** [comment]
I didn’t find anything, unfortunately. It seems to me that Rosetta’s needs are just hardcoded into the kernel.

**Comment by roolebo** [comment]
@saagarjha @peterzheng98 Apple has released [xnu source code from macOS 11.0.1 ](https://opensource.apple.com/source/xnu/xnu-7195.50.7.100.1/)and there's this bit in `ACTLR_EL1` to enable TSO:
```
#define ACTLR_EL1_EnTSO   (1ULL << 1)
```

**Comment by saagarjha** [comment]
Hmm, I'll have to take a look–at first glance it looks fairly in line with what I expected, although there is certainly nuance that I didn't know about. Thanks for the heads up!

**Comment by peterzheng98** [comment]
That's interesting! Thanks for the details!!

**Comment by saagarjha** [comment]
The latest code should find the offsets automatically, so I'm going to close this issue. If it doesn't work for you, feel free to reopen this!
