### ISSUE TITLE
How to set kern.tso_enable for all threads

### ISSUE THREAD

**Issue by aarunach08** [saagarjha/TSOEnabler#3]
I am totally new to kernel programming, and hence, request you to pardon my ignorance.

I tried replicating your approach to enable TSO for macOS BigSur 11.2.3. I didn't know how to determine the address for thread_bind_cluster_type in KDK. However, I verified that kernel release version was kernel.release.t8020 (matching yours).

I was able to build and load TSOEnabler. But, I am unable to set kern.tso_enable for all threads.

When I tried the below, I got the following error:
sudo sysctl kern.tso_enable=1
kern.tso_enable: 0
sysctl: kern.tso_enable=1: Unknown error: 1970991808

Could you kindly let me know what I am missing here? Thanks for the help.

**Comment by saagarjha** [comment]
I guess the first thing I should ask is if you're actually on a DTK? If not, the steps are probably mildly different.

**Comment by aarunach08** [comment]
No, I am not on a DTK.

Following are the steps that I did:
* Disabled SIP
* Build your TSO enable using Xcode:
xcodebuild -target TSOEnabler -configuration Release -arch arm64e
* Dragged and placed TSOEnabler.kext on to /Library/Extensions/
* sudo chmod -R 755 TSOEnabler.kext
* sudo kextload /Library/Extensions/TSOEnabler.kext

Kindly let me know if there is something else that I need to do. Thanks for the help.

**Comment by saagarjha** [comment]
If you are on a M1 Mac, you will need to change the `TSO_OFFSET`; see #1 for how to do that. There is no need to do anything with `thread_bind_cluster_type` on those machines because the cores implement the same ISA, so you can comment out everything related to that. (That is, the only thing you should need is thread pointer-relative read/write.)

**Comment by aarunach08** [comment]
Thanks, I will give that a try. 

Once I change the TSO offset to 0x4f8 and load back the kernel extension, should I just write 1 to kern.tso_enable to enable it for all threads? Would the following work:
sudo kern.tso_enable=1

**Comment by saagarjha** [comment]
That sysctl applies to the thread you set it on. If you'd like to enable it for a process I suggest you augment or hook thread creation to toggle TSO, as you'll get confusing results otherwise.

**Comment by aarunach08** [comment]
Thanks. I wrote a C-program to set the flag through sysctlbyname. I notice that the flag was 0 before the write and it got set to 1 after the write (from log info. below). 

However, I still get "Unknown error: 1971062360" on the terminal. I presume the write to kern.tso_enable was not successful.

Following are the debug info. from log:2021-03-24 18:08:32.859970-0700 0x102bd    Default     0x0                  0      0    kernel: (TSOEnabler) TSOEnabler: got request from 1207
2021-03-24 18:08:32.859971-0700 0x102bd    Default     0x0                  0      0    kernel: (TSOEnabler) TSOEnabler: TSO is 0
2021-03-24 18:08:32.859984-0700 0x102bd    Default     0x0                  0      0    kernel: (TSOEnabler) TSOEnabler: got request from 1207
2021-03-24 18:08:32.859985-0700 0x102bd    Default     0x0                  0      0    kernel: (TSOEnabler) TSOEnabler: setting TSO to 1
2021-03-24 18:08:32.859986-0700 0x102bd    Default     0x0                  0      0    kernel: (TSOEnabler) TSOEnabler: binding to performance core
2021-03-24 18:08:32.859993-0700 0x102bd    Default     0x0                  0      0    kernel: (TSOEnabler) TSOEnabler: got request from 1207
2021-03-24 18:08:32.859993-0700 0x102bd    Default     0x0                  0      0    kernel: (TSOEnabler) TSOEnabler: TSO is 1

Could you kindly tell me what I am missing here? I use TSO_OFFSET of 0x4f8 for this M1 mac. Unknown error didn't correspond to any of the error codes for SYSCTL.

**Comment by saagarjha** [comment]
I'm not familiar with that error code; do you know where it might be coming from? Maybe you can just ignore it for now, if your TSO is working (here's a quick program to check:

```c
#include <pthread.h>
#include <stdbool.h>
#include <stdlib.h>

#define SIZE 10000

volatile bool done[SIZE];
volatile bool x[SIZE];
pthread_cond_t cond;

void *foo(void *bar) {
	for (int i = 0; i < SIZE; ++i) {
		x[i] = true;
		done[i] = true;
	}
	for (int i = 0; i < SIZE; ++i) {
		done[i] = false;
		x[i] = false;
	}
	return NULL;
}

int main() {
	pthread_t thread;
	while (true) {
		pthread_create(&thread, NULL, foo, NULL);
		for (int i = 0; i < SIZE; ++i) {
			if (done[i]) {
				if (!x[i]) {
					return 0;
				}
			}
		}
		pthread_join(thread, NULL);
		for (int i = 0; i < SIZE; ++i) {
			done[i] = false;
			x[i] = false;
		}
	}
}
```
; it'll exit if TSO is not enabled)

**Comment by aarunach08** [comment]
Thanks a lot.

I had set tso_enable as part of your foo() function and the program terminated. Is this the right way to test this? If yes, I think TSO is not enabled in my M1. I still see the logs mentioning that the kernel code set it to 1 though.
void *foo(void *bar) {
        int tsoEnable = 1;
        size_t sizeOfFlag = sizeof(tsoEnable);
        int errNum = sysctlbyname("kern.tso_enable", NULL, &sizeOfFlag, &tsoEnable, sizeOfFlag);

        for (int i = 0; i < SIZE; ++i) {
                x[i] = true;
                done[i] = true;
        }   
        for (int i = 0; i < SIZE; ++i) {
                done[i] = false;
                x[i] = false;
        }   
        return NULL;
}

**Comment by saagarjha** [comment]
Did you also set it on the main thread?

**Comment by aarunach08** [comment]
Thanks. I didn't earlier.

When I set it for the main thread as well, the program ran for over 6 minutes and then terminated. I assumed that if TSO was enabled, it would run indefinitely. Isn't that the case?

**Comment by saagarjha** [comment]
Hmm, that is strange. How long does it run when you have TSO off?

**Comment by aarunach08** [comment]
It terminates in less than 2 seconds with TSO off.

I ran this program on an x86 machine too and noticed the program to terminate after running for a few minutes.

**Comment by saagarjha** [comment]
The latest code on master has an updated test program, as well as a interposable dynamic library that can help you enable TSO on all threads, so I'm going to close this for now. If you're still having issues, please feel free to reopen this!
