### ISSUE TITLE
Address for unslid_printf and unslid_thread_bind_cluster_type is not changed in patch "macOS Big Sur 11.1 (20C69)"

### ISSUE THREAD

**Issue by zongyao8752593** [saagarjha/TSOEnabler#4]
Hi, I checked your patch "macOS Big Sur 11.1 (20C69)", there is only comment changes, 
Are the address of unslid_printf and unslid_thread_bind_cluster_type not changed from "macOS Big Sur 11.1 Beta (20C5061b)"?

I know nothing about macos kernel, I just want to enable TSO on my M1 (macos big sur 11.1 20c69).

Thanks,
yao

**Comment by saagarjha** [comment]
On an M1 Mac, you likely do not have to deal with those functions: see #1 for more details.

(FWIW, yes, the addresses did not change between those two versions, but do note at that time I was only testing on the DTK.)

**Comment by zongyao8752593** [comment]
Hi saagarjha,
Thanks for your quick response.
I removed the code related with thread_bind_cluster_type, and tried to set TSO_OFFSET to 0x4e8/0x4f8/0x4e0/0x4a8
but it doesn't work. The testing program mentioned in issue3 terminates after several minutes running, which should be in a dead loop, never terminates. (It seems the same issue @aarunach08  mentioned). I set the flag of TSO_enable both in the main thread and sub thread.
I suspect that should the thread be running on performance core, not the efficiency core, how should it be guaranteed?
Or the TSO_OFFSET is not correct?

Thanks,
Yao

**Comment by saagarjha** [comment]
Those registers should automatically be set by the kernel when transitioning back into userspace; TSOEnabler just marks a process as being "Rosetta" and lets the kernel deal with whatever work is necessary to support this.

Having `thread_bind_cluster_type` cause a reboot suggests that the machine has panicked. Do you have a crash log? Perhaps your offset are not correct.

**Comment by zongyao8752593** [comment]
Hi saagarjha, I tried the code for t8101 from https://github.com/losfair/TSOEnabler 
thread_bind_cluster_type works and there is no kernel crash, but the testing program terminated after 2 minutes.
Also, I modified 

> static void (*thread_bind_cluster_type)(thread_t, char, **bool**);
since when schedule to a performance core, there are two ways: one is soft-bond, the other one is hard-bond.
The last bool parameter is set to false if it is hard-bond.
If using hard-bond, it won't be switched to E core. and I observed the cpu usage, the threads are not scheduled to E core.

So the issue is, the testing program terminated, TSO is not enabled properly. Perhaps TSO Offset is not right?
I also tried 0x4e8/0x4e8. Both doesn't work as expected.

**Comment by zongyao8752593** [comment]
Or maybe we should set thread_pointer[TSO_OFFSET] = 255, I don't know which bit should be set to 1.

**Comment by saagarjha** [comment]
Again, I will have to look into this more to be sure, but I am pretty sure the the flag is just a simple boolean, although you can try setting it to 255 to see if that helps. I am thinking that my test program is broken rather than TSO–perhaps you can try finding anther test while I figure out what is wrong with this one?

**Comment by zongyao8752593** [comment]
Yeah, I tried to set thread_pointer[TSO_OFFSET] = 255, doesn't work.
The test program I used is attached.

[tso_test.zip](https://github.com/saagarjha/TSOEnabler/files/6464180/tso_test.zip)

**Comment by saagarjha** [comment]
I have access to a M1 Mac now, so I'll try to take another look at this at some point.

**Comment by db7** [comment]
I created a PR with some hints how to find the TSO_OFFSET (!5). That may help you @zongyao8752593.

**Comment by db7** [comment]
Regarding dropping `thread_bind_cluster_type` as commented on !5. Actually, for performance measurements it could be useful to be able to set the cluster type of individual threads (even if that means that threads running on E cores cannot use TSO). So, I think that an additional interface specifically to call this function could be useful. 

I tried looking for this function in the binary, but had a hard time, although I found it in the source code of the kernel. Do you have a tip how to find it?

**Comment by saagarjha** [comment]
Consulting the KDK is an easy way to do this.

**Comment by saagarjha** [comment]
@zongyao8752593 Please try this program:

```c
#include <pthread.h>
#include <stdatomic.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdlib.h>

atomic_uint barrier;
atomic_uint data[10000];

void *writer(void *unused) {
	(void)unused;
	while (true) {
		for (size_t i = 0; i < sizeof(data) / sizeof(*data); ++i) {
			atomic_fetch_add_explicit(data + i, 1, memory_order_relaxed);
		}
		atomic_fetch_add_explicit(&barrier, 1, memory_order_release);
	}
	return NULL;
}

void *reader(void *unused) {
	(void)unused;
	unsigned int count = 0;
	while (true) {
		for (size_t i = 0; i < sizeof(data) / sizeof(*data) - 1; ++i) {
			unsigned int value2 = atomic_load_explicit(data + i + 1, memory_order_relaxed);
			unsigned int value1 = atomic_load_explicit(data + i, memory_order_relaxed);
			if (value1 < value2) {
				exit(0);
			}
		}

		while (count == atomic_load_explicit(&barrier, memory_order_acquire))
			;
		++count;
	}
	return NULL;
}

int main() {
	pthread_t writer_thread;
	pthread_t reader_thread;
	pthread_create(&writer_thread, NULL, writer, NULL);
	pthread_create(&reader_thread, NULL, reader, NULL);
	pthread_join(reader_thread, NULL);
	pthread_join(writer_thread, NULL);
}
```

I'm still [not very sure if the program is well-formed](https://twitter.com/_saagarjha/status/1398091061239566341) but it seems to compile into something close to what I wanted. Running this on my Mac natively, it exits almost immediately, but under TSO I don't think it does.

**Comment by db7** [comment]
We have been testing the TSO with something like this: https://gist.github.com/db7/2e368c8c8b1eaa8ea360e44bdb209306

**Comment by saagarjha** [comment]
I've committed the above program to master, although @db7's seems like it works too. Closing with the assumption that it works now.
