### ISSUE TITLE
How safe is this?

### ISSUE THREAD

**Issue by Techcable** [saagarjha/TSOEnabler#7]
Or rather, how likely is this to brick my new laptop? 😉

**Comment by db7** [comment]
I've been using this with Mac Mini and it works fine.

**Comment by saagarjha** [comment]
It's unlikely to brick your machine, but kernel panics are not unlikely and those might cause data loss. I wouldn't run this on a machine that you have important things on. (Well, I would, but you probably shouldn't.)
