### ISSUE TITLE
@saagarjha @peterzheng98 Apple has released [xnu source code from macOS 11.0.1 ](https://opensource.apple.com/source/xnu/xnu-7195.50.7.100.1/) and there's this bit in `ACTLR_EL1` to enable TSO:

### ISSUE THREAD

**Issue by Readm** [saagarjha/TSOEnabler#8]
@saagarjha @peterzheng98 Apple has released [xnu source code from macOS 11.0.1 ](https://opensource.apple.com/source/xnu/xnu-7195.50.7.100.1/) and there's this bit in `ACTLR_EL1` to enable TSO:
```
#define ACTLR_EL1_EnTSO   (1ULL << 1)
```

But that's not all. There's one more place that defines enable TSO bit on A12Z:
```
#define ARM64_REG_HID9                         S3_0_c15_c9_0
#define ARM64_REG_HID9_TSOAllowDcZvaWC         (1ULL << 26)
#define ARM64_REG_HID9_TSOSerializeVLDmicroops (1ULL << 29)
#define ARM64_REG_HID9_TSO_ENABLE              (1ULL << 16)

#define ARM64_REG_EHID10                        S3_0_c15_c10_1
#define ARM64_REG_EHID10_DisZVATemporalTSO      (1ULL << 49)
```

_Originally posted by @roolebo in https://github.com/saagarjha/TSOEnabler/issues/1#issuecomment-754679236_

**Comment by Readm** [comment]
Hi all, I am very courious about these bits. Does anyone know the function of them?
I have tried Enable/Disable them, the performance are different in some cases, but I didn't find any memory order differece. 
Thanks for all possible helps.

**Comment by saagarjha** [comment]
How are you modifying them?

**Comment by Readm** [comment]
Using [Asahi Linux](https://asahilinux.org/), not MacOS.
BTY, I saw you find code sequence by
https://github.com/saagarjha/TSOEnabler/blob/4b4ae3daf116baf99e83d6d223d316641f3e6c94/TSOEnabler/TSOEnabler.c#L28
How do you find that? does it means the TSO enabling is always together with other bits? (`0x70`), Do you know other bits related to TSO?

**Comment by saagarjha** [comment]
The original sequence was actually found by @osy, I just wrote the code to verify that it enables total store ordering. The code in the kernel appears to always toggle it together with the other bits. They're not TSO related, but they are helpful to Rosetta: https://github.com/apple-oss-distributions/xnu/blob/e7776783b89a353188416a9a346c6cdb4928faad/osfmk/arm64/proc_reg.h#L1986

**Comment by Readm** [comment]
Thanks, but these parts seem related to TSO, any related information?

```
#define ARM64_REG_HID9                         S3_0_c15_c9_0
#define ARM64_REG_HID9_TSOAllowDcZvaWC         (1ULL << 26)
#define ARM64_REG_HID9_TSOSerializeVLDmicroops (1ULL << 29)
#define ARM64_REG_HID9_TSO_ENABLE              (1ULL << 16)

#define ARM64_REG_EHID10                        S3_0_c15_c10_1
#define ARM64_REG_EHID10_DisZVATemporalTSO      (1ULL << 49)
```

**Comment by Readm** [comment]
I think only the last two bits are for A12Z.
The first 4 bits seems works on M1.
How do you know which one is for A12Z?

> 
> ```
> #define ARM64_REG_HID9                         S3_0_c15_c9_0
> #define ARM64_REG_HID9_TSOAllowDcZvaWC         (1ULL << 26)
> #define ARM64_REG_HID9_TSOSerializeVLDmicroops (1ULL << 29)
> #define ARM64_REG_HID9_TSO_ENABLE              (1ULL << 16)
> 
> #define ARM64_REG_EHID10                        S3_0_c15_c10_1
> #define ARM64_REG_EHID10_DisZVATemporalTSO      (1ULL << 49)
> ```

**Comment by saagarjha** [comment]
I don't really know what ARM64_REG_EHID10  is used for on A12Z but this is the only use I can find in the 12.5 kernel:

```
fffffe00072584f0	mrs	x13, S3_0_C15_C10_1
fffffe00072584f4	orr	x13, x13, #0x80000
fffffe00072584f8	msr	S3_0_C15_C10_1, x13
```

**Comment by Readm** [comment]
And it seems not related to this bit. 
Thanks for the discussion! I'll close this issue.

> I don't really know what ARM64_REG_EHID10 is used for on A12Z but this is the only use I can find in the 12.5 kernel:
> 
> ```
> fffffe00072584f0	mrs	x13, S3_0_C15_C10_1
> fffffe00072584f4	orr	x13, x13, #0x80000
> fffffe00072584f8	msr	S3_0_C15_C10_1, x13
> ```
